#!/usr/bin/env python3
"""Build, sign and catalogue every hidden GPU driver package.

Input : tools/gpu-driver/catalog.json
Output: kernel/drivers/gpu/pins.h        generated matching table + public key
        build/gpu-drivers/packages/*.ndpk signed packages (uploaded to GitHub)
        build/gpu-drivers/catalog.json    human readable listing + hashes

The kernel only ever downloads the one package whose PCI vendor/device list
matches the primary display adapter.  Nothing here is embedded in the ISO;
only the *table* and the *public key* are, so a new driver version can be
published without rebuilding the OS as long as the version number rises.
"""
from pathlib import Path
import argparse, hashlib, json, sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_gpu_module_v2 import build
import gpu_package

root = Path(__file__).resolve().parents[1]
dist = root / 'build' / 'gpu-drivers'


def c_bytes(data):
    return ','.join('0x%02x' % b for b in data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--only', help='comma separated package names')
    args = ap.parse_args()
    catalog = json.loads((root / 'tools/gpu-driver/catalog.json').read_text(encoding='utf-8'))
    only = set(args.only.split(',')) if args.only else None
    (dist / 'packages').mkdir(parents=True, exist_ok=True)
    (dist / 'work').mkdir(parents=True, exist_ok=True)
    listing = []
    entries = []
    for pkg in catalog['packages']:
        name = pkg['name']
        vendor = int(pkg['vendor'], 16)
        devices = [int(d, 16) for d in pkg['devices']]
        entries.append((pkg, vendor, devices))
        if only and name not in only:
            continue
        header_device = devices[0] if len(devices) == 1 else 0xFFFF
        meta = build([root / s for s in pkg['sources']], dist / 'work' / (name + '.ndrv'), vendor, header_device)
        module = (dist / 'work' / (name + '.ndrv')).read_bytes()
        package = gpu_package.pack(name, pkg['version'], module)
        assert gpu_package.verify(package), 'signature self-check failed for ' + name
        (dist / 'packages' / (name + '.ndpk')).write_bytes(package)
        info = gpu_package.describe(package)
        info.update(vendor=pkg['vendor'], devices=pkg['devices'], title=pkg['title'], status=pkg['status'],
                    trial=pkg['trial'], module_memory_bytes=meta['memory_bytes'])
        listing.append(info)
        print('%-10s v%-3d %7d bytes  sha256 %s' % (name, pkg['version'], len(package), info['sha256'][:16]))
    # Generated kernel table (identical for a partial --only build).
    out = ['/* GENERATED by scripts/build_gpu_catalog.py from tools/gpu-driver/catalog.json - do not edit.',
           ' * Contains the matching table and the ECDSA P-256 *public* key that the kernel trusts for',
           ' * downloaded GPU driver packages. No driver code is embedded in the OS image. */',
           '#ifndef NEXIS_GPU_PINS_H', '#define NEXIS_GPU_PINS_H', '#include "catalog.h"',
           'static const unsigned char gpu_signing_key[65] __attribute__((unused)) = {%s};' % c_bytes(gpu_package.public_key()),
           'static const char *const gpu_mirrors[] __attribute__((unused)) = {%s};' % ','.join('"%s"' % m for m in catalog['mirrors']),
           '#define GPU_MIRROR_COUNT %d' % len(catalog['mirrors'])]
    for pkg, vendor, devices in entries:
        out.append('static const uint16_t gpu_devices_%s[] __attribute__((unused)) = {%s};' % (pkg['name'], ','.join('0x%04x' % d for d in devices)))
    out.append('static const gpu_catalog_entry gpu_catalog[] __attribute__((unused)) = {')
    for pkg, vendor, devices in entries:
        out.append(' {"%s",0x%04x,gpu_devices_%s,%d,%d,%d},' % (pkg['name'], vendor, pkg['name'], len(devices),
                                                              pkg['min_version'], 1 if pkg['trial'] else 0))
    out += ['};', '#define GPU_CATALOG_COUNT %d' % len(entries), '#endif', '']
    (root / 'kernel/drivers/gpu/pins.h').write_text('\n'.join(out), newline='\n')
    # Public listing: merge with any previous full listing so --only keeps other entries.
    previous = {}
    listing_file = dist / 'catalog.json'
    if listing_file.exists():
        previous = {p['name']: p for p in json.loads(listing_file.read_text()).get('packages', [])}
    for item in listing:
        previous[item['name']] = item
    listing_file.write_text(json.dumps({'format': 1, 'packages': [previous[k] for k in sorted(previous)]}, indent=2) + '\n')
    print('wrote kernel/drivers/gpu/pins.h with %d catalog entries' % len(entries))


if __name__ == '__main__':
    main()
